spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermanagement
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mangesh@09
  application:
    name: USER-SERVICE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: MYSQL




server:
  port: 9091


