spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billingmanagement
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mangesh@09

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: MYSQL




server:
  port: 9092


